apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build: 
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-295003
  artifacts: # ist of all things to be built
    - image: us.gcr.io/ticketing-dev-295003/auth
      context: auth # folder that contain above image
      docker:
        dockerfile: Dockerfile
      sync: #how to handle any file change 
        manual:
          - src: 'src/**/*.ts' # watch all the .ts files in src dir
            dest: . # sync files to container
